/**
 * Model Finder - Finite model enumeration
 * 
 * Equivalent to Mace4 - finds finite models or counterexamples.
 */

import { parse } from './parser.js';
import { Model, ModelResult, ModelOptions, DEFAULTS } from './types/index.js';
import type { ASTNode } from './types/index.js';
import { extractSignature, astToString } from './utils/ast.js';
import { createGenericError } from './types/errors.js';
import { symmetricMappings, allMappings, allFunctionTables, allTuples } from './utils/enumerate.js';
import { SATEngine } from './engines/sat.js';
import { groundFormula } from './utils/grounding.js';
import { clausify } from './clausifier.js';

export type { Model, ModelResult };

/**
 * Model Finder for finite domains
 */
export class ModelFinder {
    private timeout: number;
    private maxDomainSize: number;
    private satEngine = new SATEngine();

    constructor(timeout: number = 5000, maxDomainSize: number = 10) {
        this.timeout = timeout;
        this.maxDomainSize = maxDomainSize;
    }

    /**
     * Find a model satisfying the premises
     */
    async findModel(
        premises: string[],
        options?: ModelOptions
    ): Promise<ModelResult> {
        const opts = { ...DEFAULTS, ...options };
        const startTime = Date.now();
        const startSize = 1;
        const endSize = opts.maxDomainSize ?? this.maxDomainSize;

        try {
            // Parse all premises
            const asts = premises.map(p => parse(p));

            // Extract signature (predicates, constants, functions)
            const signature = extractSignature(asts);

            // Try increasing domain sizes
            for (let size = startSize; size <= endSize; size++) {
                if (Date.now() - startTime > (opts.maxSeconds ?? 30) * 1000) {
                    return { success: false, result: 'timeout' };
                }

                const shouldUseSAT = opts.useSAT === true || (opts.useSAT === 'auto' && size > opts.satThreshold!);

                const model = shouldUseSAT
                    ? await this.findModelSAT(premises, size, opts)
                    : this.tryDomainSize(asts, signature, size, opts);

                if (model) {
                    return {
                        success: true,
                        result: 'model_found',
                        model,
                        interpretation: this.formatModel(model)
                    };
                }
            }

            return { success: false, result: 'no_model' };
        } catch (e) {
            const error = e instanceof Error ? e : createGenericError('ENGINE_ERROR', String(e));
            return {
                success: false,
                result: 'error',
                error: error.message
            };
        }
    }

    /**
     * Find a model using SAT solver
     */
    private async findModelSAT(
        premises: string[],
        size: number,
        opts: ModelOptions
    ): Promise<Model | null> {
        // 1. Ground all premises
        const grounded = premises.map(p => {
            const ast = parse(p);
            return `(${astToString(groundFormula(ast, { domainSize: size }))})`;
        }).join(' & ');

        // 2. Clausify
        const result = clausify(grounded);
        if (!result.success || !result.clauses) return null;

        // 3. SAT solve
        const satResult = await this.satEngine.checkSat(result.clauses);
        if (!satResult.sat) return null;

        // 4. Decode
        return this.decodeSATModel(satResult.model!, size);
    }

    /**
     * Decode SAT model into Model structure
     */
    private decodeSATModel(satModel: Map<string, boolean>, size: number): Model {
        const predicates = new Map<string, Set<string>>();

        for (const [varName, val] of satModel) {
            if (!val) continue;
            const m = varName.match(/^(\w+)(?:\(([^)]*)\))?$/);
            if (m) {
                const [, pred, argsStr] = m;
                // Constants like '0', '1' are also returned as true vars in some cases if they are propositions,
                // but usually predicates look like p(0,1).
                // We should be careful about internal vars generated by clausifier if any.
                if (pred.startsWith('$')) continue; // Skip internal vars

                if (!predicates.has(pred)) predicates.set(pred, new Set());
                predicates.get(pred)!.add(argsStr || '');
            }
        }

        return {
            domainSize: size,
            domain: Array.from({ length: size }, (_, i) => i),
            predicates,
            constants: new Map(), // Constants are folded into predicates or grounding
            functions: new Map(), // Functions are flattened to predicates
            interpretation: ''
        };
    }

    /**
     * Find a counterexample (model where premises true but conclusion false)
     */
    async findCounterexample(
        premises: string[],
        conclusion: string,
        options?: ModelOptions
    ): Promise<ModelResult> {
        // A counterexample is a model of premises ∧ ¬conclusion
        const negatedConclusion = `-(${conclusion.replace(/\.$/, '')})`;

        const result = await this.findModel(
            [...premises, negatedConclusion],
            options
        );

        if (result.success) {
            result.interpretation = `Counterexample found: The premises are satisfied but the conclusion '${conclusion}' is FALSE in this model.`;
        }

        return result;
    }

    /**
     * Try to find a model of given domain size using backtracking
     */
    private tryDomainSize(
        asts: ASTNode[],
        signature: {
            predicates: Map<string, number>;
            functions: Map<string, number>;
            constants: Set<string>;
            variables: Set<string>;
        },
        size: number,
        options: ModelOptions
    ): Model | null {
        const domain = Array.from({ length: size }, (_, i) => i);
        const useSymmetry = options.enableSymmetry !== false; // Default to true if not specified

        // Assign constants to domain elements
        const constantAssignments = this.enumerateConstants(
            Array.from(signature.constants),
            domain,
            useSymmetry
        );

        for (const constants of constantAssignments) {
            // Enumerate function interpretations
            const functionInterpretations = this.enumerateFunctions(
                signature.functions,
                domain
            );

            for (const functions of functionInterpretations) {
                // Enumerate predicate interpretations
                const predicateInterpretations = this.enumeratePredicates(
                    signature.predicates,
                    domain
                );

                for (const predicates of predicateInterpretations) {
                    const model: Model = {
                        domainSize: size,
                        domain,
                        predicates,
                        constants,
                        functions,
                        interpretation: ''
                    };

                    if (this.checkAllFormulas(asts, model)) {
                        model.interpretation = this.formatModel(model);
                        return model;
                    }
                }
            }
        }

        return null;
    }

    /**
     * Enumerate all possible constant assignments
     */
    private *enumerateConstants(
        constants: string[],
        domain: number[],
        useSymmetry: boolean
    ): Generator<Map<string, number>> {
        if (useSymmetry) {
            yield* symmetricMappings(constants, domain.length);
        } else {
            yield* allMappings(constants, domain);
        }
    }

    /**
     * Enumerate all possible predicate interpretations
     */
    private *enumeratePredicates(
        predicates: Map<string, number>,
        domain: number[]
    ): Generator<Map<string, Set<string>>> {
        const predList = Array.from(predicates.entries());
        yield* this.enumPredsHelper(predList, domain, new Map());
    }

    private *enumPredsHelper(
        preds: [string, number][],
        domain: number[],
        current: Map<string, Set<string>>
    ): Generator<Map<string, Set<string>>> {
        if (preds.length === 0) { yield new Map(current); return; }
        const [[name, arity], ...rest] = preds;
        const tuples = [...allTuples(domain, arity)];
        const numSubsets = 1 << tuples.length;

        for (let mask = 0; mask < numSubsets; mask++) {
            const ext = new Set<string>();
            for (let i = 0; i < tuples.length; i++) {
                if (mask & (1 << i)) ext.add(tuples[i].join(','));
            }
            current.set(name, ext);
            yield* this.enumPredsHelper(rest, domain, current);
        }
    }

    /**
     * Enumerate all possible function interpretations
     */
    private *enumerateFunctions(
        functions: Map<string, number>,
        domain: number[]
    ): Generator<Map<string, Map<string, number>>> {
        const funcList = Array.from(functions.entries());
        yield* this.enumFuncsHelper(funcList, domain, new Map());
    }

    private *enumFuncsHelper(
        funcs: [string, number][],
        domain: number[],
        current: Map<string, Map<string, number>>
    ): Generator<Map<string, Map<string, number>>> {
        if (funcs.length === 0) { yield new Map(current); return; }
        const [[name, arity], ...rest] = funcs;
        for (const table of allFunctionTables(arity, domain)) {
            current.set(name, table);
            yield* this.enumFuncsHelper(rest, domain, current);
        }
    }

    /**
     * Check if all formulas are satisfied in the model
     */
    private checkAllFormulas(
        asts: ASTNode[],
        model: Model
    ): boolean {
        for (const ast of asts) {
            if (!this.evaluate(ast, model, new Map())) {
                return false;
            }
        }
        return true;
    }

    /**
     * Evaluate a formula in a model under an assignment
     */
    private evaluate(
        node: ASTNode,
        model: Model,
        assignment: Map<string, number>
    ): boolean {
        switch (node.type) {
            case 'predicate': {
                const args = (node.args || []).map(a => this.evaluateTerm(a, model, assignment));
                const key = args.join(',');
                const extension = model.predicates.get(node.name!);
                return extension?.has(key) ?? false;
            }

            case 'and':
                return this.evaluate(node.left!, model, assignment) &&
                    this.evaluate(node.right!, model, assignment);

            case 'or':
                return this.evaluate(node.left!, model, assignment) ||
                    this.evaluate(node.right!, model, assignment);

            case 'not':
                return !this.evaluate(node.operand!, model, assignment);

            case 'implies':
                return !this.evaluate(node.left!, model, assignment) ||
                    this.evaluate(node.right!, model, assignment);

            case 'iff':
                return this.evaluate(node.left!, model, assignment) ===
                    this.evaluate(node.right!, model, assignment);

            case 'forall':
                return model.domain.every(d => {
                    const newAssign = new Map(assignment);
                    newAssign.set(node.variable!, d);
                    return this.evaluate(node.body!, model, newAssign);
                });

            case 'exists':
                return model.domain.some(d => {
                    const newAssign = new Map(assignment);
                    newAssign.set(node.variable!, d);
                    return this.evaluate(node.body!, model, newAssign);
                });

            case 'equals': {
                const left = this.evaluateTerm(node.left!, model, assignment);
                const right = this.evaluateTerm(node.right!, model, assignment);
                return left === right;
            }

            default:
                return false;
        }
    }

    /**
     * Evaluate a term to a domain element
     */
    private evaluateTerm(
        node: ASTNode,
        model: Model,
        assignment: Map<string, number>
    ): number {
        switch (node.type) {
            case 'variable':
                return assignment.get(node.name!) ?? 0;
            case 'constant':
                return model.constants.get(node.name!) ?? 0;
            case 'function': {
                const args = (node.args || []).map(a => this.evaluateTerm(a, model, assignment));
                const table = model.functions.get(node.name!);
                return table?.get(args.join(',')) ?? 0;
            }
            default:
                return 0;
        }
    }

    /**
     * Format model as human-readable string
     */
    private formatModel(model: Model): string {
        const lines: string[] = [];
        lines.push(`Domain size: ${model.domainSize}`);
        lines.push(`Domain: {${model.domain.join(', ')}}`);

        if (model.constants.size > 0) {
            lines.push('Constants:');
            for (const [name, value] of model.constants) {
                lines.push(`  ${name} = ${value}`);
            }
        }

        if (model.functions.size > 0) {
            lines.push('Functions:');
            for (const [name, table] of model.functions) {
                const entries = Array.from(table.entries())
                    .map(([args, val]) => `(${args})->${val}`)
                    .join(', ');
                lines.push(`  ${name}: {${entries}}`);
            }
        }

        lines.push('Predicates:');
        for (const [name, extension] of model.predicates) {
            const tuples = Array.from(extension).map(s => `(${s})`).join(', ');
            lines.push(`  ${name}: {${tuples}}`);
        }

        return lines.join('\n');
    }
}

/**
 * Create a model finder instance
 */
export function createModelFinder(timeout?: number, maxDomainSize?: number): ModelFinder {
    return new ModelFinder(timeout, maxDomainSize);
}
